# @format

name: Publish Appointment Service to Docker Hub and Docker image

on:
    pull_request_target:
        types:
            - "closed"
        branches:
            - "appointment"
jobs:
    push-to-registry:
        if: github.event.pull_request.merged == true
        name: Push to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Check for merge
              uses: actions/github-script@v6
              with:
                  script: |
                      github.event.pull_request.merged === true
                  fail-on-stderr: false

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: habib18/appointme-appointment
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: ./services/appointment
                  push: true
                  tags: ${{steps.meta.outputs.tags}}
