# @format

name: Publish Auth Service to Docker Hub and Docker image

on:
    pull_request_review:
        branches:
            - "auth"
jobs:
    push-to-registry:
        name: Push to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: habib18/appointme-auth
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: ./services/auth
                  push: true
                  tags: ${{steps.meta.outputs.tags}}
