# @format

on:
    push:
        branches:
            - "auth-develop"

jobs:
    demo-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Action Started"
            - name: Checkout
              uses: actions/checkout@v4
            - name: User Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install all dependencies
              run: npm Install
            - name: Run Tests
              run: npm test
            - run: echo "All tests passed"
