# @format

name: Publish Auth Service to Docker Hub and Docker image

on:
    push:
        branches:
            - "auth"
jobs:
    push-to-registry:
        name: Push to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
            # - name: Set up QEMU
            #   uses: docker/setup-qemu-action@v1
            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v1
            - name: print DockerHub password
              run: echo "DockerHub_pass:" ${{secrets.DOCKERHUB_PASSWORD}}
            - name: print DockerHub username
              run: echo "DockerHub_user:" ${{secrets.DOCKERHUB_USERNAME}}
            # - name: Login to DockerHub
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }} # habib18
                  password: ${{ secrets.DOCKERHUB_PASSWORD }} # @alhabib18
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: habib18/appointme-auth
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: ./services/auth
                  push: true
                  tags: ${{steps.meta.outputs.tags}}
