# @format

on:
    push:
        branches:
            - "payment-develop"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Action Started"
            - name: Checkout
              uses: actions/checkout@v4
            - name: User Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install all dependencies
              run: npm install
              working-directory: ./services/payment
            - name: Run Tests
              run: npm test
              working-directory: ./services/payment
            - run: echo "All tests passed"
